name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff
    - name: Run Ruff formatter fix
      run: ruff format .
    - name: Run Ruff linter
      run: ruff check .

  smoke-test-spark-image:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v4
    - name: Build Spark Docker image
      run: docker build . --file spark.Dockerfile --tag spark-gpx:test
    - name: Run container and import packages
      run: >
        docker run --rm spark-gpx:test
        python -c "import pandas; import pyspark; from delta import configure_spark_with_delta_pip; import gpxpy; import dash; print('Imports successful!')"